name: C/C++ CI for Windows Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    # Запускаємо роботу на віртуальній машині з Windows
    runs-on: windows-latest

    steps:
    # Крок 1: Завантажуємо код з репозиторію
    - name: Checkout repository
      uses: actions/checkout@v4

    # Крок 2: Налаштовуємо MSBuild (компілятор Visual Studio)
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # Крок 3: Збираємо проєкт (файл .sln)
    # ВАЖЛИВО: Переконайтеся, що назва файлу 'Padcher.sln' є правильною.
    - name: Build Solution
      run: msbuild.exe Padcher.sln /p:Configuration=Release

    # Крок 4 (Опціонально): Завантажити готову програму як артефакт
    # Це дозволить вам завантажити .exe файл прямо зі сторінки Actions.
    # Щоб увімкнути, видаліть символ '#' з початку наступних рядків.
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: Patcher-Executable
    #     path: Patcher/Release/Patcher.exe
