name: C/C++ CI for Windows Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Solution
      run: msbuild.exe Padcher.sln /p:Configuration=Debug
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Padcher-Executable
        path: x64/Debug/Padcher.exe
    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v2
      with:
        # Шлях до файлів, які потрібно завантажити.
        # Дія автоматично видалить старий Patcher.exe і завантажить новий.
        files: x64/Debug/Padcher.exe
        
        # Решта ваших параметрів залишаються
        tag_name: dev
        name: "Dev Build"
        body: "Auto Build Devoloper Build."
        prerelease: true
