name: C/C++ CI for Windows Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
       - name: Draft New Release
  # You may pin to the exact commit or the version.
  # uses: samkbit/gh-action-ts-auto-release-draft@c1109bf2105f9513e6523df0e94014be247f3a7d
  uses: samkbit/gh-action-ts-auto-release-draft@v1.0.0
  with:
    # The GITHUB_TOKEN used to authenticate to the current repository
    repo-token: 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
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Solution
      run: msbuild.exe Patcher.sln /p:Configuration=Debug
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Padcher-Executable
        path: x64/Debug/Patcher.exe
    
    
          
