name: C/C++ CI for Windows Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild.exe Patcher.sln /p:Configuration=Debug
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Padcher-Executable
        path: x64/Debug/Patcher.exe
 - name: Release Draft
  # You may pin to the exact commit or the version.
  # uses: crs-k/release-draft@b232aaf8608c0ba7df6d7c6382fffa238230e9b1
  uses: crs-k/release-draft@v0.7.2
  with:
    # Target of release. Default: default branch
    commitish: beta
    # Semver bump type. Options: major, minor, patch, premajor, preminor, prepatch, or prerelease.  Default level is patch. Only one version may be specified.
    bump: prepatch
