name: C/C++ CI for Windows Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Solution
      run: msbuild.exe Patcher.sln /p:Configuration=Debug
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Padcher-Executable
        path: x64/Debug/Patcher.exe
    - name: Upload assets to a Release
  # You may pin to the exact commit or the version.
  # uses: AButler/upload-release-assets@45be2facf3acc71812c1c17b4cefef5f6e8cac8a
      uses: AButler/upload-release-assets@v3.0.1
      with:
    # A glob of the files to upload
        files: x64/Debug/Patcher.exe
    # The tag name of the release to upload to (if not specified then the release that triggered the workflow is used)
        release-tag: 1
    # The ID of the release to upload to (if not specified then the release that triggered the workflow is used)
        release-id: dev
    # secrets.GITHUB_TOKEN
        repo-token: $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
