name: C/C++ CI for Windows Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest


         steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: msbuild.exe Patcher.sln /p:Configuration=Release

    - name: List all files in the workspace
      run: dir /s
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Patcher-Executable
        path: Patcher/Release/Patcher.exe
